### ISSUE TITLE
投稿：【蔡徐坤】放荡不羁电音之舞

### ISSUE THREAD

**Issue by zymzs** [ldqk/kichiku.icu#2]
【蔡徐坤】放荡不羁电音之舞
=======
码率：
```
video: 720p 1827kbps
audio: 320kbps
```
原视频链接：[视频链接](https://www.bilibili.com/video/av48828477)
视频下载链接：[百度网盘下载链接](https://pan.baidu.com/s/1Wh98tvIYyKzTxpqe0D_fCQ)
提取码：wmj7

**Comment by zymzs** [comment]
另外，建议ldqk建立一个网页来索引每个视频

**Comment by ldqk** [comment]
这个视频哔哩哔哩上面有，应该是不会被和谐的
