### ISSUE TITLE
摔跤的骗♂子我问你 & 暗黑夜♂店

### ISSUE THREAD

**Issue by Emilelu** [ldqk/kichiku.icu#4]
《摔跤的骗♂子我问你》的码率：480P
《暗黑夜♂店》的码率：720P
打包在一起了，链接: https://pan.baidu.com/s/1cZyCNyUo1o-GbmAs3cI_tQ 提取码: mass
解压密码：1

**Comment by ldqk** [comment]
感谢分享

**Comment by Vandarkdark** [comment]
文艺♂ 复兴？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ldqk/kichiku.icu"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 中午1:19
收件人:&nbsp;"ldqk/kichiku.icu"<kichiku.icu@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ldqk/kichiku.icu] 摔跤的骗♂子我问你 &amp; 暗黑夜♂店 (#4)





 
Closed #4.
