### ISSUE TITLE
水♂手

### ISSUE THREAD

**Issue by gkfans** [ldqk/kichiku.icu#6]
水♂手 (钢琴耗子) 720P:https://50t-my.sharepoint.com/:v:/g/personal/tubby_custard_mod_obagg_com/EbjLNRLJWixCmVaqtyE3AxcBALaPqa69-P2Mb0EHNSGXcQ?e=HsfCYK

水♂手（许van强）720P:https://50t-my.sharepoint.com/:v:/g/personal/tubby_custard_mod_obagg_com/EZoYneopN2hHii4lXcWhweAB1LR1K337FIRe3piW4kZupQ?e=m0779s

**Comment by ldqk** [comment]
赞美之心，要是有弹幕文件就更好了
