### ISSUE TITLE
幸存下来的

### ISSUE THREAD

**Issue by iaso2h** [ldqk/kichiku.icu#7]
评论区看到有好几位老哥声称收藏了上千鬼畜，随便点进去看看了还有一些没有被下架的。有一些剧情向的不知道收不收录，比如拳皇系列。有一些哲学视频失效下架了的话，我用Chrome扩展Btool能看一部分原来的标题和封面，然后在网上搜居然搜到一个盗视频到虎牙的。虎牙的那几个视频码率应该够高了，也没加什么水印，就是没弹幕，可惜可惜。

https://www.bilibili.com/video/BV1Us411Y7cq （这个up主有极多的作品没有被和谐）
https://www.bilibili.com/video/BV1hW411i7W5
https://www.bilibili.com/video/BV1kW411u7HZ
https://www.bilibili.com/video/BV1mW411F7VR
https://www.bilibili.com/video/BV1dp411R7fP
https://www.bilibili.com/video/BV11s411g74u
https://www.bilibili.com/video/av9753843
https://www.bilibili.com/video/BV1zt411u7aX
https://www.bilibili.com/video/BV1yx411L7zK
https://www.bilibili.com/video/BV1gW411t7Sb
https://www.bilibili.com/video/BV1gx411i72u

https://v.huya.com/play/12198376.html
https://v.huya.com/play/9813704.html
https://v.huya.com/play/9100688.html
https://v.huya.com/play/9896278.html

**Comment by ldqk** [comment]
卧槽，来晚了，好多已经被和谐了，老哥还有缓存没？

**Comment by iaso2h** [comment]
我用edge和vivaldi打开`bilibili.com`的域名的全部正常。不太确定你是不是碰到了这种类似的情况，用firefox打开会显示视频不见，但是在地址栏删掉`https://`字样回车一次还是可以打开的。还有，用手机客户端搜索栏输入`video/`后面的BV号也能打开进去

**Comment by ldqk** [comment]
是真的被和谐了，前几个链接都已经没了

**Comment by ldqk** [comment]
已经更新到仓库里了，感谢分享
